export const regions = [
  "",
  "DR NORD-PAS-DE-CALAIS",
  "DR PICARDIE",
  "DR ILE-DE-FRANCE OUEST",
  "DR ILE-DE-FRANCE EST",
  "DR PARIS",
  "DR NORMANDIE",
  "DR BRETAGNE",
  "DR PAYS DE LA LOIRE",
  "DR CENTRE-VAL DE LOIRE",
  "DR POITOU-CHARENTES",
  "DR LIMOUSIN",
  "DR AQUITAINE NORD",
  "DR PYRENEES ET LANDES",
  "DR LANGUEDOC-ROUSSILLON",
  "DR NORD MIDI-PYRENEES",
  "DR MIDI-PYRENEES SUD",
  "DR PROVENCE-ALPES DU SUD",
  "DR COTE D AZUR",
  "DR AUVERGNE",
  "DR SILLON RHODANIEN",
  "DR ALPES",
  "DR BOURGOGNE",
  "DR ALSACE FRANCHE-COMTE",
  "DR LORRAINE",
  "DR CHAMPAGNE-ARDENNE",
].sort((a, b) => a.localeCompare(b));

export const regions_obj = [
  { value: "", label: "---", center: [0, 0] },
  ...[
    { value: "DR NORD-PAS-DE-CALAIS", label: "DR NORD-PAS-DE-CALAIS", center: [50.4808, 2.7936] },
    { value: "DR PICARDIE", label: "DR PICARDIE", center: [49.6483, 2.6218] },
    { value: "DR ILE-DE-FRANCE OUEST", label: "DR ILE-DE-FRANCE OUEST", center: [48.866669, 2.33333] },
    { value: "DR ILE-DE-FRANCE EST", label: "DR ILE-DE-FRANCE EST", center: [48.866669, 2.33333] },
    { value: "DR PARIS", label: "DR PARIS", center: [48.866669, 2.33333] },
    { value: "DR NORMANDIE", label: "DR NORMANDIE", center: [48.8798704, 0.1712529] },
    { value: "DR BRETAGNE", label: "DR BRETAGNE", center: [48.18463495500992, -2.8454880553279187] },
    { value: "DR PAYS DE LA LOIRE", label: "DR PAYS DE LA LOIRE", center: [47.468401, -0.555] },
    { value: "DR CENTRE-VAL DE LOIRE", label: "DR CENTRE-VAL DE LOIRE", center: [47.902964, 1.909251] },
    { value: "DR POITOU-CHARENTES", label: "DR POITOU-CHARENTES", center: [46.5818, 0.3352] },
    { value: "DR LIMOUSIN", label: "DR LIMOUSIN", center: [45.8333, 1.25] },
    { value: "DR AQUITAINE NORD", label: "DR AQUITAINE NORD", center: [44.837789, -0.57918] },
    { value: "DR PYRENEES ET LANDES", label: "DR PYRENEES ET LANDES", center: [43.3, -0.3667] },
    { value: "DR LANGUEDOC-ROUSSILLON", label: "DR LANGUEDOC-ROUSSILLON", center: [43.6, 3.8833] },
    { value: "DR NORD MIDI-PYRENEES", label: "DR NORD MIDI-PYRENEES", center: [0, 0] },
    { value: "DR PROVENCE-ALPES DU SUD", label: "DR PROVENCE-ALPES DU SUD", center: [43.3, 5.4] },
    { value: "DR COTE D AZUR", label: "DR COTE D'AZUR", center: [43.7, 7.2667] },
    { value: "DR AUVERGNE", label: "DR AUVERGNE", center: [45.7833, 3.0833] },
    { value: "DR SILLON RHODANIEN", label: "DR SILLON RHODANIEN", center: [45.4333, 4.4] },
    { value: "DR ALPES", label: "DR ALPES", center: [45.1667, 5.7167] },
    { value: "DR BOURGOGNE", label: "DR BOURGOGNE", center: [47.3333, 4.5] },
    { value: "DR ALSACE FRANCHE-COMTE", label: "DR ALSACE FRANCHE-COMTE", center: [47.75, 6.1667] },
    { value: "DR LORRAINE", label: "DR LORRAINE", center: [48.6833, 6.2] },
    { value: "DR CHAMPAGNE-ARDENNE", label: "DR CHAMPAGNE-ARDENNE", center: [49.25, 4.0333] },
  ].sort((a, b) => a.value.localeCompare(b.value)),
];
